# Default values for aws-canary-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

detail:
  replicaCount: 2
  namespace: apps
  name: backend-service

  serviceAccount: backend-service

  image:
    pullPolicy: Always

  service:
    type: ClusterIP
    targetPort: 3000

canaryConfig:
  - name: "latest"
    tag: "latest"
    weight: 25
  - name: "v2"
    tag: "v2.0.0"
    weight: 25
  - name: "test"
    tag: "8b5d51b"
    weight: 25
  - name: "four"
    tag: "b16425b"
    weight: 25