# Default values for aws-canary-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: "backend"
servicePort: 80
containerPort: 3000
canaryConfig:
  - name: "test"
    tag: "40ba2e8"
    weight: 50
  # - name: "feature-x"
  #   tag: "1.0.2"
  #   weight: 25
  # - name: "feature-y"
  #   tag: "1.0.1"
  #   weigth: 25